apiVersion: v1
kind: Pod
metadata:
  name: client
  labels:
    app: influxdb
spec:
  containers:
    - name: influxdb-client
      image: influxdb:1.8.2
      command: ["/bin/sh"]
      args:
        - "-c"
        - "while true; do sleep 3600; done"
